---

- name: 'Test playbook to sleep for a specified interval'
  hosts: all
  gather_facts: false
  vars:
    seconds: 30

  tasks:
    - name: sleep for a specified seconds
      pause:
        seconds: '{{ seconds }}'
