---
# Launch a job and assert that it cannot:
#   - see /var/lib/awx/projects (except for self)
#   - see /var/lib/awx/job_status
#   - see /tmp/ (except for self)
#   - see /etc/awx/settings.py
#   - see /var/log/

- hosts: all
  gather_facts: true
  vars:
    tower_tmp_dir: /tmp
    tower_projects_dir: /var/lib/awx/projects
    tower_job_status_dir: /var/lib/awx/job_status
    supervisor_log_dir: /var/log/supervisor

  tasks:
    - command: find {{tower_tmp_dir}} -mindepth 1 -maxdepth 1 -type d -name 'ansible_tower*'
      register: result
    - debug: var=result
    - name: assert that only one ansible_tower_XXXXX tempfile is visible
      assert:
        that:
          - 'result.rc == 0'
          - 'result.stdout_lines|length == 1'

    - command: find {{tower_projects_dir}} -mindepth 1 -maxdepth 1 -type d
      register: result
    - debug: var=result
    - name: assert that only one tower project directory is visible
      assert:
        that:
          - 'result.rc == 0'
          - 'result.stdout_lines|length == 1'

    - command: find {{tower_job_status_dir}} -mindapth 1 -maxdepth 1 -type f
      register: result
    - debug: var=result
    - name: assert that only one job_status file is visible
      assert:
        that:
          - 'result.rc == 0'
          - 'result.stdout_lines|length == 1'

    - command: cat /etc/tower/settings.py
      ignore_errors: true
      register: result
    - debug: var=result
    - name: assert that /etc/tower/settings.py is not readable
      assert:
        that:
          - 'result.failed'
          - '"Permission denied" in result.stderr'

    - command: find {{supervisor_log_dir}} -mindepth 1 -maxdepth 1 -type f
      ignore_errors: true
      register: result
    - debug: var=result
    - name: assert that no supervisor logs are visible
      assert:
        that:
          - 'result.failed'
          - '"Permission denied" in result.stderr'
